<a href="https://colab.research.google.com/github/VinayakRaoDikshit/VrishHub/blob/RNN_Predictor_VRD/VrishHub_Rcmd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#! gdown --id 1amHqFFKtiXSA1yLN1Ca5ugL_cOx7GkQZ
! gdown -- 1amHqFFKtiXSA1yLN1Ca5ugL_cOx7GkQZ

import pandas as pd
import re 
df = pd.read_csv('Ticker+Sector.csv')

main=df[['Issuer Name','Security Id','Igroup Name']]
main2=main
main3=pd.DataFrame()

for i in main2.index:
  if(main2.at[i,'Igroup Name']=='-'):
    main2.drop(index=[i],inplace=True)
main2   #cleaned dataframe


count=0
for i in main2.index:
  if(main.at[i,'Igroup Name']=='-'):
    count+=1
count

iput=pd.DataFrame()
iput['Ticker obtained']=['HDFC']
type(iput.at[0,'Ticker obtained'])



for i in main2.index:
  s=main2.at[i,'Security Id']
  if(re.search(s,iput.at[0,'Ticker obtained'], re.IGNORECASE)):
    print(i)
    store=i

w=main2.at[store,'Igroup Name']
print(w)

for i in main2.index:
  s=main2.at[i,'Igroup Name']
  s2=main2.at[i,'Security Id']
  if(re.search(s,w, re.IGNORECASE)):
    print(i,' ', s,' ', s2,"\n")

Downloading...
From: https://drive.google.com/uc?id=1amHqFFKtiXSA1yLN1Ca5ugL_cOx7GkQZ
To: /content/Ticker+Sector.csv
100% 810k/810k [00:00<00:00, 95.3MB/s]

/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

4
Finance
4   Finance   HDFC

15   Finance   BAJFINANCE

38   Finance   CRISIL

46   Finance   IFCI

65   Finance   FGP

66   Finance   PHCAP

82   Finance   GFLLIMITED

83   Finance   GLFL

99   Finance   INDLEASE

100   Finance   MARGOFIN

130   Finance   LICHSGFIN

134   Finance   HYBRIDFIN

137   Finance   MAHSCOOTER

155   Finance   PEL

171   Finance   PRIMESECU

181   Finance   RAMAPETRO

211   Finance   VHL

215   Finance   MPILCORPL

230   Finance   BAJAJHLDNG

271   Finance   SUNRINV

274   Finance   DSINVEST

275   Finance   CENTRUM

278   Finance   IITL

279   Finance   INDPRUD

280   Finance   TATAINVEST

281   Finance   JAYBHCR

286   Finance   ZSWASTSA

296   Finance   INDIANVSH

341   Finance   ZSVTRADI

342   Finance   ZSVARAJT

343   Finance   SALSAIN

348   Finance   TILAK

350   Finance   UNIJOLL

363   Finance   ZSATYASL

378   Finance   STDBAT

384   Finance   CONFINT

386   Finance   GDTRAGN

388   Finance   RIDHISYN

411   Finance   CHOLAHLDNG

425   Finance   ALFREDHE

443   Finance   SHYMINV

463   Finance   AQFINTECH

474   Finance   MANCREDIT

487   Finance   STANROS

493   Finance   ISHWATR

494   Finance   TERRAFORM

599   Finance   PIONRINV

604   Finance   LKPFIN

605   Finance   MNPLFIN

607   Finance   KIDUJA

608   Finance   KEYCORP

609   Finance   SHIKHARLETR

611   Finance   RAJATH

615   Finance   JPTRLES

628   Finance   SMIFS

635   Finance   FINKURVE

636   Finance   HBLEAS

637   Finance   SHRICON

638   Finance   STRLGUA

639   Finance   SULABEN

648   Finance   VOLLF

652   Finance   INDINFO

653   Finance   BANASFN

668   Finance   BOMOXY-B1

682   Finance   ZHINDHSG

687   Finance   MODRNSH

699   Finance   THACKER

703   Finance   MADHUSE

704   Finance   YAMNINV

710   Finance   SAKTHIFIN

711   Finance   EASYFIN

712   Finance   SATINDLTD

716   Finance   VBDESAI

718   Finance   1STCUS

720   Finance   WSFX

722   Finance   RKDAGRRTL

727   Finance   CANFINHOME

730   Finance   SHRIRAMFIN

731   Finance   CHOLAFIN

732   Finance   SAGARSYST

733   Finance   IDINFO

734   Finance   VLSFINANCE*

735   Finance   INDCEMCAP

736   Finance   ADMANUM

737   Finance   MEHIF

738   Finance   INTRGLB

740   Finance   CREST

742   Finance   GUJCRED

744   Finance   DHARFIN

747   Finance   VCKCAP

748   Finance   BHARAT

749   Finance   CAPITALT

750   Finance   USHAKIRA

753   Finance   PANINDIAC

754   Finance   SAHARAHOUS

755   Finance   NDASEC

756   Finance   GSBFIN

757   Finance   MORARKFI

760   Finance   TIMESGTY

761   Finance   SODFC

762   Finance   REGTRUS

763   Finance   AVONMORE

764   Finance   LIBORDFIN

767   Finance   ISLCONSUL

768   Finance   DCMFINSERV

769   Finance   RRFIN

770   Finance   IMCAP

772   Finance   SUGALDAM

775   Finance   GICHSGFIN

776   Finance   MATHEWE

777   Finance   AJCON

778   Finance   CHRTEDCA

779   Finance   STANCAP

780   Finance   YOGI

781   Finance   CUBIFIN

782   Finance   RELICTEC

784   Finance   BAIDFIN

786   Finance   KZLFIN

787   Finance   TRCFIN

789   Finance   MEHSECU

790   Finance   MEHTAHG

791   Finance   UGROCAP

792   Finance   SAHLIBHFI

793   Finance   ABIRAFN

794   Finance   MANSIFIN

795   Finance   SEVENHILL

796   Finance   AASTAFIN

797   Finance   MUTHTFN

798   Finance   MASTERTR

802   Finance   CNIRESLTD

803   Finance   ZSARACOM

804   Finance   WINROC

815   Finance   MRUTR

835   Finance   SILVERO

837   Finance   STEPHANOTIS

838   Finance   PRISMMEDI

839   Finance   SPVGLOBAL

843   Finance   ASHCAP

850   Finance   ZSPEEDCO

859   Finance   YASTF

861   Finance   ZSHERAPR

864   Finance   STARTECK

866   Finance   SERA

872   Finance   APOLLOFI

875   Finance   DEVITRD

879   Finance   SHRGLTR

882   Finance   POLYTEX

884   Finance   OASISEC

885   Finance   GARNETINT

899   Finance   KEYFINSER

1006   Finance   MKVENTURES

1061   Finance   3PLAND

1153   Finance   WILLIMFI

1155   Finance   WILLAMAGOR

1246   Finance   SILINV

1287   Finance   YOGISUNG

1311   Finance   BNRSEC

1316   Finance   JJFINCOR

1318   Finance   FUTURSEC

1346   Finance   MICROSE

1352   Finance   MAHAPEXLTD

1357   Finance   JMFINANCIL

1364   Finance   INDBNK

1402   Finance   DVL

1417   Finance   PIFL

1420   Finance   POONAWALLA

1560   Finance   MORGAN

1563   Finance   MIDEASTP

1626   Finance   TFCILTD

1667   Finance   ISFL

1670   Finance   INTECCAP

1675   Finance   MKTCREAT

1681   Finance   ARUNIS

1687   Finance   LASTMILE

1703   Finance   THEINVEST

1708   Finance   TITANSEC

1714   Finance   CSLFINANCE

1720   Finance   ANUPAM

1725   Finance   NPRFIN

1730   Finance   KREONFIN

1735   Finance   MONGIPA

1737   Finance   DAULAT

1742   Finance   ATHARVENT

1743   Finance   FUNDVISER

1751   Finance   KJMCFIN

1753   Finance   ARYAMAN

1754   Finance   BRIDGESE

1758   Finance   GLOBALCA

1761   Finance   RICHUNV

1773   Finance   MUKESHB

1776   Finance   KBSINDIA

1785   Finance   JINDCAP

1786   Finance   EPIC

1787   Finance   SUMEDHA

1793   Finance   SIDDHA

1800   Finance   GSLSEC

1804   Finance   AKCAPIT

1809   Finance   MANRAJH

1813   Finance   NCLRESE

1816   Finance   LADDERUP

1817   Finance   UYFINCORP

1830   Finance   GOYALASS

1840   Finance   GOWRALE

1848   Finance   INDOASIAF

1852   Finance   DYNAMICP

1854   Finance   CEEJAY

1857   Finance   ANNAINFRA

1864   Finance   CILSEC

1870   Finance   GDLLEAS

1872   Finance   CIFL

1873   Finance   ABVL

1880   Finance   RAMSONS

1890   Finance   INDIAHOME

1894   Finance   SWRNASE

1896   Finance   VISAGAR

1897   Finance   LIBORD

1902   Finance   VINTAGES

1909   Finance   UNITDCR

1917   Finance   MENAMANI

1931   Finance   SKPSEC

1936   Finance   ARMANFIN

1939   Finance   GLANCE

1945   Finance   WELLNESS

1946   Finance   NLFL

1947   Finance   MANAPPURAM

1954   Finance   RANDER

1957   Finance   CITIPOR

1958   Finance   DHRUVCA

1962   Finance   ANERI

1964   Finance   OPTIFIN

1965   Finance   PARAGONF

1972   Finance   NIKKIGL

1974   Finance   KINETRU

1975   Finance   ELIXIR

1976   Finance   TRISHAKT

1979   Finance   CINDRELL

1981   Finance   LEADFIN

1989   Finance   AVAILFC

1990   Finance   INTCAPM

1991   Finance   MARUTISE

1994   Finance   ROSELABS

1995   Finance   CHARMS

2001   Finance   BERVINL

2002   Finance   GUJINV

2008   Finance   CHOICEIN

2016   Finance   HASTIFIN

2017   Finance   UPSURGE

2029   Finance   MEGACOR

2032   Finance   SYTIXSE

2033   Finance   SUNGOLD

2055   Finance   STEP2COR

2060   Finance   SOFTRAKV

2068   Finance   JHACC

2074   Finance   BERYLSE

2075   Finance   RAP

2077   Finance   BAMPSL

2080   Finance   CGCL

2096   Finance   TOKYOFIN

2098   Finance   THIRDFIN

2103   Finance   INANISEC

2109   Finance   PRITHVIEXCH

2116   Finance   PRISMFN

2122   Finance   BIOGEN

2123   Finance   GKCONS

2139   Finance   MUNOTHFI

2143   Finance   INDUSFINL

2146   Finance   TRINITYLEA

2153   Finance   ANJANIFIN

2175   Finance   VERTEX

2178   Finance   SHREMETAL

2188   Finance   ODYCORP

2191   Finance   SAMINDUS

2198   Finance   RBGUPTA

2207   Finance   ADIEXRE

2208   Finance   ABHICAP

2212   Finance   SAGARPROD

2216   Finance   BRIJLEAS

2220   Finance   SMCREDT

2232   Finance   GUJSTATFIN

2235   Finance   MINOLTAF

2251   Finance   HBSTOCK

2252   Finance   SIELFNS

2259   Finance   NSIL

2265   Finance   TCFCFINQ

2268   Finance   BLBLIMITED

2273   Finance   KJMCCORP

2280   Finance   VAARAD

2287   Finance   HBPOR

2306   Finance   PNBGILTS

2334   Finance   TRANSCOR

2358   Finance   KAMAHOLD

2366   Finance   BLIL

2414   Finance   IIFL

2419   Finance   JSWHL

2429   Finance   IDFC

2464   Finance   M&MFIN

2483   Finance   INDICAP

2526   Finance   PFC

2528   Finance   TFL

2552   Finance   HARYNACAP

2575   Finance   NAGREEKCAP

2579   Finance   PAISALO

2585   Finance   RELIGARE

2589   Finance   EDELWEISS

2613   Finance   NAHARCAP

2615   Finance   RECLTD

2618   Finance   DHANI

2624   Finance   BAJAJFINSV

2653   Finance   BENGALASM

2668   Finance   ESSARSEC

2684   Finance   TAMBOLI

2703   Finance   WELINV

2731   Finance   KICL

2732   Finance   BFINVEST

2733   Finance   SUMMITSEC

2734   Finance   INOVSYNTH

2735   Finance   STEL

2741   Finance   DHUNINV

2744   Finance   PFS

2745   Finance   MUTHOOTFIN

2750   Finance   DELPHIFX

2755   Finance   L&TFH

2768   Finance   ONELIFECAP

2779   Finance   PMCFIN

2780   Finance   FUTSOL

2784   Finance   PYXISFIN

2808   Finance   SRGHFL

2809   Finance   COMCL

2811   Finance   CASPIAN

2816   Finance   TRIOMERC

2826   Finance   COMFINCAP

2829   Finance   REPCOHOME

2832   Finance   KIFS

2840   Finance   IFINSEC

2846   Finance   IBULHSGFIN

2847   Finance   MMLF

2848   Finance   ALSL

2849   Finance   GCMCOMM

2859   Finance   SRGSFL

2860   Finance   ACFSL

2861   Finance   STELLAR

2862   Finance   JPOLYINVST

2866   Finance   BPCAP

2870   Finance   ARNOLD

2888   Finance   KIRANVYPAR

2892   Finance   MANGIND

2893   Finance   VFL

2901   Finance   GOLDLINE

2902   Finance   SHARPINV

2905   Finance   GCMCAPI

2908   Finance   WESTLEIRES

2909   Finance   NAM

2911   Finance   SPS

2912   Finance   MONEYBOXX

2913   Finance   WORTH

2914   Finance   TPROJECT

2915   Finance   AMARSEC

2916   Finance   CTL

2919   Finance   JTAPARIA

2920   Finance   RLFL

2923   Finance   ARMAN

2934   Finance   TTIENT

2936   Finance   TOYAMSL

2937   Finance   GAJANANSEC

2939   Finance   RTFL

2942   Finance   QGO

2943   Finance   PURSHOTTAM

2947   Finance   NAYSAA

2953   Finance   ETIL

2955   Finance   SUCHITRA

2957   Finance   ARYACAPM

2960   Finance   VGCL

2966   Finance   NIYOGIN

2967   Finance   ASIACAP

2968   Finance   AKASHDEEP

2969   Finance   GBFL

2970   Finance   GILADAFINS

2976   Finance   JMJFIN

2981   Finance   SCC

2982   Finance   PANAFIC

2984   Finance   AMARNATH

2985   Finance   CSL

2986   Finance   NEXUSSURGL

2988   Finance   GALADAFIN

2989   Finance   EMERALD

2992   Finance   OCTAL

2996   Finance   VANICOM

3002   Finance   KARNAVATI

3005   Finance   SONAL

3006   Finance   ALFL

3012   Finance   SHREESEC

3022   Finance   NEIL

3023   Finance   STARHFL

3025   Finance   SSPNFIN

3037   Finance   CITL

3042   Finance   NORTHLINK

3045   Finance   PML

3048   Finance   SUJALA

3054   Finance   VBIND

3055   Finance   SARVOTTAM

3064   Finance   HELPAGE

3066   Finance   AIIL

3067   Finance   DFL

3070   Finance   SGFIN

3074   Finance   SRESTHA

3075   Finance   SAUMYA

3087   Finance   SURYAINDIA

3090   Finance   AMRAFIN

3097   Finance   SYMBIOX

3101   Finance   BINDALAGRO

3106   Finance   CANOPYFIN

3123   Finance   KRISHNACAP

3124   Finance   ACME

3131   Finance   SATIN

3138   Finance   BRIPORT

3139   Finance   RFSL

3147   Finance   TFSL

3153   Finance   TFLL

3154   Finance   GARBIFIN

3155   Finance   SMARTFIN

3156   Finance   RAJKOTINV

3157   Finance   ADCON

3163   Finance   NAVIGANT

3164   Finance   GROVY

3172   Finance   VALLEY

3173   Finance   APOORVA

3176   Finance   FMEC

3181   Finance   SCL

3183   Finance   SHIVA

3186   Finance   ORACLECR

3191   Finance   BCLENTERPR

3197   Finance   BFLAFL

3201   Finance   DAL

3203   Finance   SHIVKAMAL

3205   Finance   IFINSER

3206   Finance   HILIKS

3214   Finance   ADVIKCA

3224   Finance   MUDRA

3226   Finance   SUPERIOR

3228   Finance   FRANKLIN

3231   Finance   EQUITAS

3235   Finance   UJJIVAN

3236   Finance   RSDFIN

3238   Finance   PILANIINVS

3249   Finance   MAXVIL

3251   Finance   BAZELINTER

3252   Finance   JLL

3287   Finance   VISCO

3295   Finance   ARCFIN

3307   Finance   SUPRAP

3308   Finance   PNBHOUSING

3310   Finance   REGENCY

3312   Finance   SALEM

3316   Finance   CMBL

3325   Finance   MTPL

3327   Finance   TRU

3337   Finance   LLFICL

3342   Finance   KDLL

3343   Finance   ONTIC

3354   Finance   ESCORP

3357   Finance   CLFL

3360   Finance   KANUNGO

3362   Finance   HUDCO

3379   Finance   GANGESSEC

3406   Finance   RELHOME

3424   Finance   MASFIN

3483   Finance   ACFL

3508   Finance   INDOSTAR

3537   Finance   CREDITACC

3552   Finance   AAVAS

3569   Finance   ARYAN

3583   Finance   HIKLASS

3588   Finance   SPACAPS

3598   Finance   JYOTIN

3637   Finance   SPANDANA

3641   Finance   IIFLWAM

3643   Finance   MUFIN

3687   Finance   COLABCLOUD

3691   Finance   EASUN

3693   Finance   ASSAMENT

3700   Finance   VARDHANCFL

3707   Finance   SBICARD

3743   Finance   REGIS

3754   Finance   MAXINDIA

3784   Finance   RFLL

3785   Finance   IRFC

3787   Finance   HOMEFIRST

3844   Finance   APTUS

4017   Finance   FUSION

4022   Finance   FIVESTAR

4040   Finance   AHL

4077   Finance   SUNDARMFIN

4092   Finance   ASHIKACR

In [ ]:
main2

,Issuer Name,Security Id,Igroup Name
0,ABB India Limited,ABB,Electrical Equipment
1,Aegis Logistics Ltd.,AEGISLOG,Gas
2,Amara Raja Batteries Ltd,AMARAJABAT,Auto Components
3,"Ambalal Sarabhai Enterprise Ltd.,",AMBALALSA,Pharmaceuticals & Biotechnology
4,Housing Development Finance Corp.Lt,HDFC,Finance
...,...,...,...
4090,Quantum Asset Management Co. Pvt. Ltd.,QNIFTY,Capital Markets
4091,Motilal Oswal Mutual Fund-Permitted,MOM50,Capital Markets
4092,Ashika Credit Capital Limited,ASHIKACR,Finance
4093,Gradiente Infotainment Limited,GRADIENTE,Media
4094,Madras Fertilizers Ltd,MADRASFERT,Fertilizers & Agrochemicals

In [ ]:
import pandas as pd
df = pd.read_csv('Ticker+Sector.csv')

In [ ]:
df

In [ ]:
df[df['Igroup Name'=='Gas']]

KeyError: ignored

In [ ]:
main=df[['Issuer Name','Security Id','Igroup Name']]
#main.at[1]

In [ ]:
cell=main.at[4104,'Igroup Name']
cell

'-'

In [ ]:
main2=main
main3=pd.DataFrame()
print(type(main3))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
count=0
for i in main2.index:
  if(main2.at[i,'Igroup Name']=='-'):
    main2.drop(index=[i],inplace=True)

/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [ ]:
main2
#cleaned dataframe

,Issuer Name,Security Id,Igroup Name
0,ABB India Limited,ABB,Electrical Equipment
1,Aegis Logistics Ltd.,AEGISLOG,Gas
2,Amara Raja Batteries Ltd,AMARAJABAT,Auto Components
3,"Ambalal Sarabhai Enterprise Ltd.,",AMBALALSA,Pharmaceuticals & Biotechnology
4,Housing Development Finance Corp.Lt,HDFC,Finance
...,...,...,...
4090,Quantum Asset Management Co. Pvt. Ltd.,QNIFTY,Capital Markets
4091,Motilal Oswal Mutual Fund-Permitted,MOM50,Capital Markets
4092,Ashika Credit Capital Limited,ASHIKACR,Finance
4093,Gradiente Infotainment Limited,GRADIENTE,Media
4094,Madras Fertilizers Ltd,MADRASFERT,Fertilizers & Agrochemicals

In [ ]:
count=0
for i in main2.index:
  if(main.at[i,'Igroup Name']=='-'):
    count+=1

count

0

In [ ]:
iput=pd.DataFrame()
iput['Ticker obtained']=['HDFC']
type(iput.at[0,'Ticker obtained'])

str

In [ ]:
import re 

for i in main2.index:
  s=main2.at[i,'Security Id']
  if(re.search(s,iput.at[0,'Ticker obtained'], re.IGNORECASE)):
    print(i)

4

In [ ]:
main.index

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            4085, 4086, 4087, 4088, 4089, 4090, 4091, 4092, 4093, 4094],
           dtype='int64', length=3944)

In [ ]:
main2.index

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            4085, 4086, 4087, 4088, 4089, 4090, 4091, 4092, 4093, 4094],
           dtype='int64', length=3944)

In [ ]:
type(main)

pandas.core.frame.DataFrame

In [ ]:
res=main.isnull()
res

      Issuer Name  Security Id  Igroup Name
0           False        False        False
1           False        False        False
2           False        False        False
3           False        False        False
4           False        False        False
...           ...          ...          ...
4090        False        False        False
4091        False        False        False
4092        False        False        False
4093        False        False        False
4094        False        False        False

[3944 rows x 3 columns]

In [ ]:
# main2=main[main[['Issuer Name','Security Id','Igroup Name']!='-']]
main[main['Igroup Name'=='Gas']]

KeyError: ignored